// Flat config, one file for all four workspaces. Deliberately minimal: recommended rules only, no
// type-checked rules. Typecheck already runs `tsc --noEmit` per package, so type-aware lint rules
// would mostly duplicate it at several times the runtime — lint is here for the things the compiler
// doesn't have an opinion about.
import js from "@eslint/js";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/build/**",
      "**/coverage/**",
      "**/playwright-report/**",
      "**/test-results/**",
      "infra/migrations/**", // generated by drizzle-kit
      "packages/api/src/db/meta/**",
      "**/next-env.d.ts", // generated by Next on every build
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      // TypeScript's own noUnusedLocals is the authority; the lint copy only adds noise. Keep it as
      // a warning that ignores the conventional underscore-prefixed throwaway.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // `cond ? pass(...) : fail(...)` as a statement is a deliberate idiom in the e2e scripts, and
      // the rule has an option for exactly it. Short-circuit and tagged-template statements stay
      // banned — those are usually a mistake.
      "@typescript-eslint/no-unused-expressions": [
        "error",
        { allowShortCircuit: false, allowTernary: true, allowTaggedTemplates: false },
      ],
    },
  },
  {
    // Tests reach into loose shapes on purpose — asserting on an error envelope, poking a handler
    // with a deliberately wrong payload. Requiring a named type for each would make the tests worse,
    // not safer, and the production code they exercise is still fully typed.
    files: ["**/*.test.ts", "**/*.spec.ts", "**/_testutil.ts", "**/e2e/**"],
    rules: { "@typescript-eslint/no-explicit-any": "off" },
  },
  {
    // Plain Node scripts outside any workspace tsconfig: the Claude Code hooks, and the test
    // harnesses that drive them. fetch/AbortSignal are Node 20+ globals (session-brief.mjs queries
    // MemOS with them); setTimeout is used for the MCP smoke test's request timeout.
    files: [".claude/hooks/**/*.mjs", "testing/**/*.mjs", "scripts/**/*.mjs", "sdk/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        Buffer: "readonly",
        console: "readonly",
        fetch: "readonly",
        AbortSignal: "readonly",
        setTimeout: "readonly",
      },
    },
  },
);
